[package]
name = "mundis-compute-budget-program"
version = "1.9.15"
homepage = "https://mundis.io/"
repository = "https://github.com/mundisnetwork/axis"
authors = ["Mundis Maintainers <maintainers@mundis.io>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
mundis-program-runtime = { path = "../../program-runtime", version = "=1.9.15" }
mundis-sdk = { path = "../../sdk", version = "=1.9.15" }

[lib]
crate-type = ["lib"]
name = "mundis_compute_budget_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
