[package]
name = "mundis-transaction-status"
version = "1.9.17"
authors = ["Mundis Maintainers <maintainers@mundis.io>"]
repository = "https://github.com/mundisnetwork/axis"
homepage = "https://mundis.io/"
license = "Apache-2.0"
edition = "2021"

[dependencies]
base64 = "0.12.3"
bincode = "1.3.3"
bs58 = "0.4.0"
Inflector = "0.11.4"
lazy_static = "1.4.0"
log = "0.4.14"
serde = "1.0.130"
serde_derive = "1.0.103"
serde_json = "1.0.72"
mundis-account-decoder = { path = "../account-decoder", version = "=1.9.17" }
mundis-measure = { path = "../measure", version = "=1.9.17" }
mundis-metrics = { path = "../metrics", version = "=1.9.17" }
mundis-runtime = { path = "../runtime", version = "=1.9.17" }
mundis-sdk = { path = "../sdk", version = "=1.9.17" }
mundis-vote-program = { path = "../programs/vote", version = "=1.9.17" }
mundis-memo-program = { path = "../programs/memo", version = "=1.9.17" }
mundis-token-program = { path = "../programs/token", version = "=1.9.17" }
mundis-token-account-program = { path = "../programs/token-account", version = "=1.9.17" }
thiserror = "1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
