[package]
name = "mundis-test-harness"
version = "1.9.15"
authors = ["Mundis Maintainers <maintainers@mundis.io>"]
repository = "https://github.com/mundisnetwork/axis"
license = "Apache-2.0"
homepage = "https://mundis.io/"
edition = "2021"

[dependencies]
async-trait = "0.1.51"
borsh = "0.9.1"
base64 = "0.12.3"
bincode = "1.3.3"
chrono-humanize = "0.2.1"
futures = "0.3"
log = "0.4.14"
serde = "1.0.130"
mundis-logger = { path = "../logger", version = "=1.9.15" }
mundis-program = { path = "../sdk/program", version = "=1.9.15" }
mundis-program-runtime = { path = "../program-runtime", version = "=1.9.15" }
mundis-runtime = { path = "../runtime", version = "=1.9.15" }
mundis-sdk = { path = "../sdk", version = "=1.9.15" }
mundis-send-transaction-service = { path = "../send-transaction-service", version = "=1.9.15" }
mundis-vote-program = { path = "../programs/vote", version = "=1.9.15" }
mundis-token-program = { path = "../programs/token", version = "=1.9.15" }
mundis-token-account-program = { path = "../programs/token-account", version = "=1.9.15" }
tarpc = { version = "0.27.2", features = ["full"] }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tokio-serde = { version = "0.8", features = ["bincode"] }
tokio-stream = "0.1"

[dev-dependencies]
assert_matches = "1.5.0"