[package]
name = "mundis-send-transaction-service"
version = "1.9.16"
authors = ["Mundis Maintainers <maintainers@mundis.io>"]
repository = "https://github.com/mundisnetwork/axis"
homepage = "https://mundis.io/"
license = "Apache-2.0"
edition = "2021"

[dependencies]
log = "0.4.14"
mundis-logger = { path = "../logger", version = "=1.9.16" }
mundis-metrics = { path = "../metrics", version = "=1.9.16" }
mundis-runtime = { path = "../runtime", version = "=1.9.16" }
mundis-sdk = { path = "../sdk", version = "=1.9.16" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
